name: release
on:
  push:
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GEM_NAME: "lock"
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v
        id: release
        with:
          release-type: ruby
          package-name: ${{ env.GEM_NAME }}
          bump-minor-pre-major: true
          version-file: "lib/${{ env.GEM_NAME }}/version.rb"
      - uses: actions/checkout@v2
        if: steps.release.outputs.release_created
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: steps.release.outputs.release_created
      - run: bundle
        if: steps.release.outputs.release_created
      - name: publish gem
        if: steps.release.outputs.release_created
        env:
           GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
