name: ruby

on:
  push:
    branches: [master]
  pull_request:
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec spec
    - name: Run rubocop
      run: bundle exec rubocop
